person_classes:
  - person

bag_classes:
  - backpack
  - handbag
  - suitcase
  - trolley_bag

everyday_classes:
  - phone
  - laptop
  - bottle

risk_classes:
  - suspicious_object
  - dangerous_object
  - knife
  - gun
<<<<<<< HEAD
  - weapon
=======
>>>>>>> b00d683fc072ab36a0f7aa2b9ffefddf6ca9afcb
